# Generated by Django 6.0.3 on 2026-03-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('nome_produto', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_shopee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_promocional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comprimento_cm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('largura_cm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('altura_cm', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome_produto'],
            },
        ),
    ]
